<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4MG5hVt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4MG5hVt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4MG5hVt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4MG5hVt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4MG5hVt\App_KernelDevDebugContainer([
    'container.build_hash' => '4MG5hVt',
    'container.build_id' => '28c38ed8',
    'container.build_time' => 1676720094,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4MG5hVt');
